### PR TITLE
update for 19.0

### PR DESCRIPTION
**Pull request by Gsantomaggio**
update for Erlang/OTP version 19.0

### CODE REVIEW

**Comment by jasonmcintosh** [comment]
Thanks for the update!

**Comment by jasonmcintosh** [comment]
BTW, give me a day to get the RPM Rebuilt :)

**Comment by michaelklishin** [comment]
Was this ever rebuild and published? This RPM badly needs updated because RabbitMQ Chef cookbook depends on it. I will submit 2 PRs but we'd rather avoid forking it permanently.

**Comment by jasonmcintosh** [comment]
@michaelklishin You should be full maintainer now on the project so if you ever need to bump, you can do so in this repository :)  I've also published and rpmbuild your pull requests.

**Pull request merged**
